#!/bin/bash -l


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "=========================================================="

module load fastqc

INFILE=`find /myPath/SN0126773/*.fq.gz | sed 's/.fq.gz$//'| head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

fastqc -o /myPath/1fastqc  ${INFILE}.fq.gz ;

