#!/bin/bash -l


# Now let's keep track of some information just in case anything goes wrong
echo "=========================================================="
echo "Starting on : $(date)"
echo "Running on node : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID : $JOB_ID"
echo "Current job name : $JOB_NAME"
echo "Task index number : $SGE_TASK_ID"
echo "=========================================================="

module load samtools


INFILE=`find /restricted/projectnb/chengcancer/Simon/project/Ho_lab/0raw/SN0126773/*.bam | sed 's/.bam$//'| head -${SGE_TASK_ID} |tail -1`
echo "NOW in TASK ${SGE_TASK_ID} : PROCESSING $INFILE ..."

samtools sort -@ 4 -n  -o ${INFILE}_sorted.bam  ${INFILE}.bam 


